import function de.hshannover.f4.trust.ironsyslog.util.DroolsRuleLogger.debug
import function de.hshannover.f4.trust.ironsyslog.ifmap.IronSyslogPublisher.publishIpMac
import de.hshannover.f4.trust.ironsyslog.ep.events.IpMacEvent
import de.hshannover.f4.trust.ironsyslog.ep.events.LoginFailedEvent

declare IpMacEvent
@role(event)
@timestamp(timestamp)
end

declare LoginFailedEvent
@role(event)
@timestamp(timestamp)
end

rule "Publish IpMacEvent"
when
	$e:IpMacEvent()
then
	debug("Rule \"" + drools.getRule().getName() + "\" fired.");
	publishIpMac($e);
end

rule "Publish LoginFailedEvent"
when
	$e:LoginFailedEvent()
then
	debug("Rule \"" + drools.getRule().getName() + "\" fired.");
	publishLoginFailed($e);
end