import function de.hshannover.f4.trust.ironsyslog.util.DroolsRuleLogger.debug
import function de.hshannover.f4.trust.ironsyslog.ifmap.IronSyslogPublisher.publishIfMap
import de.hshannover.f4.trust.ironsyslog.ep.events.AggregatedLoginFailedEvent

declare AggregatedLoginFailedEvent
@role(event)
@timestamp(timestamp)
end

rule "Publish AggregatedLoginFailedEvent"
when
	$e:AggregatedLoginFailedEvent()
then
	debug("Rule \"" + drools.getRule().getName() + "\" fired.");
	publishIfMap($e);
end