import function de.hshannover.f4.trust.ironsyslog.util.DroolsRuleLogger.debug
import function de.hshannover.f4.trust.ironsyslog.ifmap.IronSyslogPublisher.publishIfMap
import de.hshannover.f4.trust.ironsyslog.ep.events.MalwareDetectedEvent

declare MalwareDetectedEvent
@role(event)
@timestamp(timestamp)
end

rule "Publish MalwareDetectedEvent"
when
	$e:MalwareDetectedEvent()
then
	debug("Rule \"" + drools.getRule().getName() + "\" fired.");
	publishIfMap($e);
end